### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by Matt-Lepley** [jmundraw/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by jmundraw** [comment]
I think I've figured it out. I've pushed the changes to heroku so you should be able to see it on mobile device.

**Comment by Matt-Lepley** [comment]
Thumbs up! Feel free to close this issue since you have fixed it!
